src/Entity/Adresse.php
<?php

namespace App\Entity;

use App\Repository\AdresseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdresseRepository::class)
 */
class Adresse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rue;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Client::class, mappedBy="idAdresse")
     */
    private $clients;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="adresse_livraison")
     */
    private $commandes;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="idAdresse")
     */
    private $users;

    public function __construct()
    {
        $this->clients = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(Client $client): self
    {
        if (!$this->clients->contains($client)) {
            $this->clients[] = $client;
            $client->setIdAdresse($this);
        }

        return $this;
    }

    public function removeClient(Client $client): self
    {
        if ($this->clients->removeElement($client)) {
            // set the owning side to null (unless already changed)
            if ($client->getIdAdresse() === $this) {
                $client->setIdAdresse(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setAdresseLivraison($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getAdresseLivraison() === $this) {
                $commande->setAdresseLivraison(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addIdAdresse($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeIdAdresse($this);
        }

        return $this;
    }
}

src/Form/AdresseType.php
<?php

namespace App\Form;

use App\Entity\Adresse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdresseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ville')
            ->add('rue')
            ->add('code_postal')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adresse::class,
        ]);
    }
}

src/Controller/AdresseController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Form\AdresseType;
use App\Repository\AdresseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/adresse')]
class AdresseController extends AbstractController
{
    #[Route('/', name: 'adresse_index', methods: ['GET'])]
    public function index(AdresseRepository $adresseRepository): Response
    {
        return $this->render('adresse/index.html.twig', [
            'adresses' => $adresseRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'adresse_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $adresse = new Adresse();
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($adresse);
            $entityManager->flush();

            return $this->redirectToRoute('adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse/new.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'adresse_show', methods: ['GET'])]
    public function show(Adresse $adresse): Response
    {
        return $this->render('adresse/show.html.twig', [
            'adresse' => $adresse,
        ]);
    }

    #[Route('/{id}/edit', name: 'adresse_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Adresse $adresse): Response
    {
        $form = $this->createForm(AdresseType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('adresse_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adresse/edit.html.twig', [
            'adresse' => $adresse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'adresse_delete', methods: ['POST'])]
    public function delete(Request $request, Adresse $adresse): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adresse->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($adresse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('adresse_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/adresse/_delete_form.html.twig
<form method="post" action="{{ path('adresse_delete', {'id': adresse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adresse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/adresse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Adresse{% endblock %}

{% block body %}
    <h1>Edit Adresse</h1>

    {{ include('adresse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('adresse_index') }}">back to list</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}

templates/adresse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse index{% endblock %}

{% block body %}
    <h1>Adresse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ville</th>
                <th>Rue</th>
                <th>Code_postal</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adresse in adresses %}
            <tr>
                <td>{{ adresse.id }}</td>
                <td>{{ adresse.ville }}</td>
                <td>{{ adresse.rue }}</td>
                <td>{{ adresse.codePostal }}</td>
                <td>
                    <a href="{{ path('adresse_show', {'id': adresse.id}) }}">show</a>
                    <a href="{{ path('adresse_edit', {'id': adresse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('adresse_new') }}">Create new</a>
{% endblock %}

templates/adresse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adresse{% endblock %}

{% block body %}
    <h1>Create new Adresse</h1>

    {{ include('adresse/_form.html.twig') }}

    <a href="{{ path('adresse_index') }}">back to list</a>
{% endblock %}

templates/adresse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresse{% endblock %}

{% block body %}
    <h1>Adresse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adresse.id }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ adresse.ville }}</td>
            </tr>
            <tr>
                <th>Rue</th>
                <td>{{ adresse.rue }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ adresse.codePostal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('adresse_index') }}">back to list</a>

    <a href="{{ path('adresse_edit', {'id': adresse.id}) }}">edit</a>

    {{ include('adresse/_delete_form.html.twig') }}
{% endblock %}